language: cpp
compiler:
  - gcc
install:
  - sudo apt-get install -y qt5-default libqt5webkit5-dev libqt5svg5-dev qttools5-dev
  - sudo apt-get install -y libraw-dev
script:
  - cmake .
  - make
notifications:
  email: false
