language: cpp
compiler:
  - gcc
install:
  - |
    sudo apt-get install -y \
      qt5-default libqt5webkit5-dev libqt5svg5-dev qttools5-dev \
      libboost-atomic-dev libboost-chrono-dev libboost-filesystem-dev \
      libboost-iostreams-dev libboost-program-options-dev \
      libboost-system-dev libboost-thread-dev \
      libeigen3-dev \
      libraw-dev \
      libfftw3-dev \
      libilmbase-dev \
      libopenexr-dev \
      libcfitsio3-dev \
      libexiv2-dev \
      libgsl0-dev
script:
  - cmake .
  - make
notifications:
  email: false
