language: cpp
compiler:
  - gcc
install:
  - |
    sudo apt-get install -y \
      qt5-default libqt5webkit5-dev libqt5svg5-dev qttools5-dev \
      libraw-dev \
      libfftw3-dev \
      libeigen3-dev
script:
  - cmake .
  - make
notifications:
  email: false
